/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EmployeeAccess = "desk" | "manager" | "owner" | "staff";

export type EmployeeStatus = "active" | "invited";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LegalEntityOwner = "salon" | "supplier";

export type LegalEntityStatus = "pending" | "verified";

export type LocationLifecycle = "ACTIVE" | "APPROVED" | "CHANGES_REQUIRED" | "CLOSED" | "DRAFT" | "RESUBMITTED" | "SUBMITTED" | "SUSPENDED" | "UNDER_REVIEW";

export type PaymentAccountStatus = "active" | "incomplete";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actorEmployeeId: string | null;
  actorName: string;
  after: Generated<string>;
  before: Generated<string>;
  businessName: Generated<string>;
  id: Generated<string>;
  locationName: Generated<string>;
  object: string;
  reason: Generated<string>;
  roleName: Generated<string>;
  source: Generated<string>;
  tenantId: string;
  ts: Generated<Timestamp>;
}

export interface Businesses {
  country: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  ownerEmployeeId: string | null;
  plan: Generated<string>;
  since: Timestamp | null;
  timingEnabled: Generated<boolean>;
  vat: string | null;
}

export interface EmployeeLocations {
  employeeId: string;
  locationId: string;
  tenantId: string;
}

export interface Employees {
  access: Generated<EmployeeAccess>;
  bookable: Generated<boolean>;
  color: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  phone: string | null;
  roleId: string | null;
  roleTitle: Generated<string>;
  status: Generated<EmployeeStatus>;
  tenantId: string;
  twofaEnabled: Generated<boolean>;
}

export interface LegalEntities {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  fiscalProfileId: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  name: string;
  ownerId: string | null;
  ownerType: LegalEntityOwner;
  status: Generated<LegalEntityStatus>;
  taxId: string | null;
  tenantId: string | null;
  vatReg: string | null;
}

export interface LegalEntityLocations {
  legalEntityId: string;
  locationId: string;
  tenantId: string;
}

export interface LocationLifecycleLog {
  actorEmployeeId: string | null;
  at: Generated<Timestamp>;
  fromState: LocationLifecycle;
  id: Generated<string>;
  locationId: string;
  reason: string | null;
  tenantId: string;
  toState: LocationLifecycle;
}

export interface Locations {
  address: string | null;
  cancelHours: Generated<number>;
  city: string | null;
  createdAt: Generated<Timestamp>;
  hours: Json | null;
  id: Generated<string>;
  invPrefix: string | null;
  lifecycle: Generated<LocationLifecycle>;
  name: string;
  online: Generated<boolean>;
  opened: Timestamp | null;
  payments: Json | null;
  phone: string | null;
  rooms: Generated<number>;
  tenantId: string;
  tz: Generated<string>;
}

export interface PaymentAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  legalEntityId: string;
  merchantId: string | null;
  provider: string | null;
  settlementRef: string | null;
  status: Generated<PaymentAccountStatus>;
  tenantId: string | null;
}

export interface RefreshTokens {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  expiresAt: Timestamp;
  familyId: string;
  id: Generated<string>;
  revokedAt: Timestamp | null;
  rotatedAt: Timestamp | null;
  tenantId: string;
  tokenHash: string;
}

export interface Roles {
  baseRoleId: string | null;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  locked: Generated<boolean>;
  name: string;
  perms: Generated<Json>;
  std: Generated<boolean>;
  tenantId: string;
}

export interface SchemaMigrations {
  version: string;
}

export interface UserCredentials {
  employeeId: string;
  passwordHash: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  auditLog: AuditLog;
  businesses: Businesses;
  employeeLocations: EmployeeLocations;
  employees: Employees;
  legalEntities: LegalEntities;
  legalEntityLocations: LegalEntityLocations;
  locationLifecycleLog: LocationLifecycleLog;
  locations: Locations;
  paymentAccounts: PaymentAccounts;
  refreshTokens: RefreshTokens;
  roles: Roles;
  schemaMigrations: SchemaMigrations;
  userCredentials: UserCredentials;
}
