/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentKind = "absence" | "appointment" | "blocked" | "chore" | "note";

export type AppointmentStatus = "booked" | "cancelled" | "confirmed" | "no_show" | "requested";

export type CheckoutStatus = "FAILED" | "PAID" | "PARTIALLY_PAID";

export type ComboStatus = "active" | "draft";

export type DiscountCodeType = "Fixed amount" | "Percentage";

export type EmployeeAccess = "desk" | "manager" | "owner" | "staff";

export type EmployeeStatus = "active" | "invited";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InvoiceStatus = "Paid" | "Refunded";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LegalEntityOwner = "salon" | "supplier";

export type LegalEntityStatus = "pending" | "verified";

export type LocationLifecycle = "ACTIVE" | "APPROVED" | "CHANGES_REQUIRED" | "CLOSED" | "DRAFT" | "RESUBMITTED" | "SUBMITTED" | "SUSPENDED" | "UNDER_REVIEW";

export type ModifierGroupType = "multi" | "single";

export type MtxStatus = "config_incomplete" | "failed" | "paid";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentAccountStatus = "active" | "incomplete";

export type PurchaseOrderStatus = "accepted" | "approval" | "cancelled" | "delivered" | "disputed" | "draft" | "partdelivered" | "partial" | "processing" | "shipped" | "submitted";

export type RegistrationStatus = "active" | "changes_required" | "declined" | "pending_review" | "resubmitted" | "under_review";

export type ScheduleExceptionSource = "MANUAL" | "PUBLIC_HOLIDAY";

export type ScheduleExceptionType = "CLOSED" | "CUSTOM_HOURS";

export type ServiceStatus = "active" | "draft";

export type StockMovementKind = "adjustment" | "delivery" | "own_use" | "sale" | "transfer_in" | "transfer_out";

export type SupportStatus = "closed" | "in_progress" | "open" | "resolved";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TimingStatus = "approved" | "dismissed" | "none" | "suggested";

export type WidgetStatus = "draft" | "live";

export interface AppointmentHistory {
  appointmentId: string;
  at: Generated<Timestamp>;
  byName: Generated<string>;
  id: Generated<string>;
  source: Generated<string>;
  tenantId: string;
  what: string;
}

export interface Appointments {
  anyEmp: Generated<boolean>;
  clientUserId: string | null;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  date: Timestamp;
  deposit: Generated<number>;
  durationMin: number;
  employeeId: string | null;
  id: Generated<string>;
  idempotencyKey: string | null;
  kind: Generated<AppointmentKind>;
  locationId: string;
  modifierNames: Generated<string[]>;
  modifierOptionIds: Generated<string[]>;
  paid: Generated<string>;
  pmoId: string | null;
  poId: string | null;
  prepMin: Generated<number>;
  price: Generated<number>;
  quoted: Json | null;
  resetMin: Generated<number>;
  serviceId: string | null;
  source: Generated<string>;
  startMin: number;
  status: Generated<AppointmentStatus>;
  tenantId: string;
  title: Generated<string>;
  variantId: string | null;
  variantLabel: string | null;
  widgetId: string | null;
}

export interface AssistantActions {
  actionId: string;
  actorEmployeeId: string | null;
  app: string;
  change: Json;
  draftId: string | null;
  fingerprint: Json | null;
  id: Generated<string>;
  reason: string | null;
  result: string;
  tenantId: string;
  ts: Generated<Timestamp>;
}

export interface AssistantDrafts {
  actionId: string;
  app: string;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  draft: Json;
  expiresAt: Timestamp;
  id: Generated<string>;
  status: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actorEmployeeId: string | null;
  actorName: string;
  after: Generated<string>;
  before: Generated<string>;
  businessName: Generated<string>;
  id: Generated<string>;
  locationName: Generated<string>;
  object: string;
  reason: Generated<string>;
  roleName: Generated<string>;
  source: Generated<string>;
  tenantId: string;
  ts: Generated<Timestamp>;
}

export interface Brands {
  country: Generated<string>;
  id: Generated<string>;
  name: string;
  owner: Generated<string>;
}

export interface BusinessCategories {
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  name: string;
  sort: Generated<number>;
}

export interface Businesses {
  address: string | null;
  assistantEnabled: Generated<boolean>;
  city: string | null;
  country: string;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  gallery: Generated<Json>;
  id: Generated<string>;
  name: string;
  ownerEmployeeId: string | null;
  phone: string | null;
  plan: Generated<string>;
  settings: Generated<Json>;
  since: Timestamp | null;
  slug: string | null;
  socials: Generated<Json>;
  timingEnabled: Generated<boolean>;
  vat: string | null;
}

export interface CategoryRequests {
  createdAt: Generated<Timestamp>;
  decidedAt: Timestamp | null;
  hqReason: Generated<string>;
  id: Generated<string>;
  kind: string;
  name: string;
  note: Generated<string>;
  status: Generated<string>;
  tenantId: string;
}

export interface CheckoutItems {
  amount: number;
  checkoutId: string;
  id: Generated<string>;
  itemClass: string;
  merchantTransactionId: string | null;
  name: string;
  qty: Generated<number>;
  sellerLegalEntityId: string | null;
  taxProfileId: string | null;
  tenantId: string;
}

export interface Checkouts {
  customerId: string | null;
  id: Generated<string>;
  invoiceId: string;
  status: Generated<CheckoutStatus>;
  tenantId: string;
  total: number;
  ts: Generated<Timestamp>;
}

export interface ClientCustomerLinks {
  clientUserId: string;
  createdAt: Generated<Timestamp>;
  customerId: string;
  tenantId: string;
}

export interface ClientFavourites {
  clientUserId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  missingSince: Timestamp | null;
  refId: string;
  tenantId: string;
}

export interface ClientPaymentMethods {
  brand: string;
  clientUserId: string;
  createdAt: Generated<Timestamp>;
  expMonth: number;
  expYear: number;
  holder: Generated<string>;
  id: Generated<string>;
  last4: string;
  provider: Generated<string>;
  providerRef: string;
}

export interface ClientNotifications {
  body: Generated<string>;
  clientUserId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  readAt: Timestamp | null;
  refId: string | null;
  refType: string | null;
  title: string;
}

export interface ClientUsers {
  avatar: string | null;
  createdAt: Generated<Timestamp>;
  dob: Timestamp | null;
  email: string;
  emailCode: string | null;
  emailCodeSentAt: Timestamp | null;
  emailVerifiedAt: Timestamp | null;
  first: Generated<string>;
  id: Generated<string>;
  lang: Generated<string>;
  last: Generated<string>;
  /**
   * Whether the customer allowed location use. NULL = never asked. A decision only — no position is ever stored.
   */
  locationAllowed: boolean | null;
  passwordHash: string;
  personalisedResults: Generated<boolean>;
  phone: string | null;
}

export interface Combos {
  category: string | null;
  createdAt: Generated<Timestamp>;
  descr: Generated<string>;
  id: Generated<string>;
  items: Generated<Json>;
  name: string;
  online: Generated<boolean>;
  pos: Generated<boolean>;
  price: number;
  regular: number;
  sort: Generated<number>;
  status: Generated<ComboStatus>;
  tenantId: string;
  validity: Generated<string>;
  vat: Generated<number>;
}

export interface CustomerActivity {
  actorEmployeeId: string | null;
  customerId: string;
  id: Generated<string>;
  meta: Generated<Json>;
  refId: Generated<string>;
  refType: Generated<string>;
  tenantId: string;
  ts: Generated<Timestamp>;
  type: string;
}

export interface Customers {
  birthday: Timestamp | null;
  blacklisted: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  custGroup: Generated<string>;
  email: string | null;
  emailVerifiedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  noShows: Generated<number>;
  note: string | null;
  phone: string | null;
  points: Generated<number>;
  premium: Json | null;
  prepaid: Generated<number>;
  since: Generated<Timestamp>;
  spend: Generated<number>;
  tags: Generated<string[]>;
  tenantId: string;
  visits: Generated<number>;
}

export interface DiscountCodes {
  active: Generated<boolean>;
  code: string;
  ends: Timestamp;
  id: Generated<string>;
  starts: Timestamp;
  tenantId: string;
  type: DiscountCodeType;
  usageLimit: number | null;
  used: Generated<number>;
  value: number;
}

export interface EmployeeLocations {
  employeeId: string;
  locationId: string;
  tenantId: string;
}

export interface Employees {
  access: Generated<EmployeeAccess>;
  avatar: string | null;
  bookable: Generated<boolean>;
  color: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  hours: Json | null;
  id: Generated<string>;
  lang: Generated<string>;
  name: string;
  phone: string | null;
  roleId: string | null;
  roleTitle: Generated<string>;
  status: Generated<EmployeeStatus>;
  tenantId: string;
  twofaEnabled: Generated<boolean>;
}

export interface EmployeeSignInLinks {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  employeeId: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  revokedAt: Timestamp | null;
  tenantId: string;
  tokenHash: string;
  usedAt: Timestamp | null;
}

export interface EmployeeSkills {
  employeeId: string;
  serviceId: string;
  tenantId: string;
}

export interface EmpTimings {
  approvedAt: Timestamp | null;
  approvedBy: string | null;
  approvedMin: number | null;
  computedAt: Timestamp | null;
  dismissedAtN: Generated<number>;
  employeeId: string;
  id: Generated<string>;
  locationId: string | null;
  observedMedianMin: number | null;
  observedN: Generated<number>;
  paceFactor: Numeric | null;
  recommendedMin: number | null;
  serviceId: string;
  source: Generated<string>;
  status: Generated<TimingStatus>;
  tenantId: string;
  variantId: string | null;
  windowFrom: Timestamp | null;
  windowTo: Timestamp | null;
}

export interface GiftCards {
  code: string;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  id: Generated<string>;
  remaining: number;
  tenantId: string;
  value: number;
}

export interface Holds {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  employeeId: string | null;
  id: Generated<string>;
  key: string;
  locationId: string;
  serviceId: string | null;
  startMin: number;
  tenantId: string;
  until: Timestamp;
}

export interface HolidayCalendarYears {
  countryCode: string;
  countryName: string;
  source: Generated<string>;
  verified: Generated<boolean>;
  year: number;
}

export interface Holidays {
  applies: Generated<string>;
  countryCode: string;
  date: Timestamp;
  id: string;
  movedFrom: Timestamp | null;
  name: string;
  type: string;
  year: number;
}

export interface HqRoles {
  customerAccess: Generated<string>;
  descr: Generated<string>;
  id: string;
  locked: Generated<boolean>;
  name: string;
  perms: Generated<Json>;
  sensitive: Generated<boolean>;
  std: Generated<boolean>;
}

export interface HqUsers {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  passwordHash: string;
  role: Generated<string>;
  status: Generated<string>;
}

export interface IntegrationEvents {
  code: string;
  fix: Generated<string>;
  id: Generated<string>;
  level: Generated<string>;
  msg: string;
  tenantId: string;
  ts: Generated<Timestamp>;
  widgetId: string | null;
}

export interface InvoiceCounters {
  locationId: string;
  next: Generated<number>;
  tenantId: string;
}

export interface InvoiceLines {
  appointmentId: string | null;
  description: string;
  id: Generated<string>;
  invoiceId: string;
  itemClass: Generated<string>;
  lineDiscount: Generated<number>;
  productId: string | null;
  qty: Generated<number>;
  serviceId: string | null;
  sort: Generated<number>;
  tenantId: string;
  unitPrice: number;
  vat: Generated<number>;
}

export interface Invoices {
  cartDiscount: Generated<number>;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  customerName: Generated<string>;
  date: Generated<Timestamp>;
  employeeId: string | null;
  employeeName: Generated<string>;
  giftAmount: Generated<number>;
  id: Generated<string>;
  idempotencyKey: string | null;
  locationId: string;
  method: string;
  number: string;
  pointsRedeemed: Generated<number>;
  promoAmount: Generated<number>;
  promoCode: string | null;
  serviceCharge: Generated<number>;
  status: Generated<InvoiceStatus>;
  tenantId: string;
  tip: Generated<number>;
  total: number;
}

export interface LastMinuteOffers {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  date: Timestamp;
  eligibleVariantIds: Generated<string[]>;
  id: Generated<string>;
  locationId: string;
  phases: Json;
  slotIds: string[];
  slots: Json;
  status: Generated<string>;
  tenantId: string;
}

export interface LegalEntities {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  fiscalProfileId: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  name: string;
  ownerId: string | null;
  ownerType: LegalEntityOwner;
  status: Generated<LegalEntityStatus>;
  taxId: string | null;
  tenantId: string | null;
  vatReg: string | null;
}

export interface LegalEntityLocations {
  legalEntityId: string;
  locationId: string;
  tenantId: string;
}

export interface LocationCatalogProducts {
  active: Generated<boolean>;
  locationId: string;
  lowStock: Generated<number>;
  openedAmount: Generated<number>;
  pos: Generated<boolean>;
  price: number;
  productId: string;
  stock: Generated<number>;
  tenantId: string;
}

export interface LocationCatalogServices {
  active: Generated<boolean>;
  durationMin: number;
  locationId: string;
  online: Generated<boolean>;
  pos: Generated<boolean>;
  prepMin: number | null;
  price: number;
  resetMin: number | null;
  serviceId: string;
  tenantId: string;
}

export interface LocationCatalogVariants {
  active: Generated<boolean>;
  durationMin: number | null;
  locationId: string;
  price: number | null;
  tenantId: string;
  variantId: string;
}

export interface LocationLifecycleLog {
  actorEmployeeId: string | null;
  at: Generated<Timestamp>;
  fromState: LocationLifecycle;
  id: Generated<string>;
  locationId: string;
  reason: string | null;
  tenantId: string;
  toState: LocationLifecycle;
}

export interface Locations {
  address: string | null;
  cancelHours: Generated<number>;
  city: string | null;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  hours: Json | null;
  id: Generated<string>;
  invPrefix: string | null;
  lat: number | null;
  lifecycle: Generated<LocationLifecycle>;
  lng: number | null;
  name: string;
  online: Generated<boolean>;
  opened: Timestamp | null;
  payments: Json | null;
  phone: string | null;
  rooms: Generated<number>;
  tenantId: string;
  tz: Generated<string>;
  zip: string | null;
}

export interface LoyaltyConfig {
  active: Generated<boolean>;
  birthday: Generated<number>;
  earnPer: Generated<number>;
  expiryMonths: Generated<number>;
  points: Generated<number>;
  step: Generated<number>;
  tenantId: string;
  welcome: Generated<number>;
  worth: Generated<number>;
}

export interface LoyaltyLedger {
  at: Generated<Timestamp>;
  customerId: string;
  id: Generated<string>;
  points: number;
  reason: string;
  ref: Generated<string>;
  tenantId: string;
}

export interface MailOutbox {
  attempts: Generated<number>;
  body: Generated<string>;
  createdAt: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  kind: string;
  messageId: string | null;
  meta: Generated<Json>;
  nextAttemptAt: Timestamp | null;
  refId: string | null;
  sentAt: Timestamp | null;
  status: Generated<string>;
  subject: string;
  tenantId: string | null;
  toEmail: string;
}

export interface MemberRecs {
  candidates: Json;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  employeeId: string | null;
  endAt: string;
  id: Generated<string>;
  locationId: string;
  normalPrice: number;
  offerId: string | null;
  recPct: number;
  recPrice: number;
  serviceId: string;
  startAt: string;
  status: Generated<string>;
  tenantId: string;
  variantId: string | null;
}

export interface MerchantTransactions {
  amount: number;
  checkoutId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idempotencyKey: string;
  legalDocRef: string | null;
  legalEntityId: string | null;
  method: string;
  paymentAccountId: string | null;
  providerRef: string | null;
  status: MtxStatus;
  tenantId: string;
}

export interface PaymentAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  legalEntityId: string;
  merchantId: string | null;
  provider: string | null;
  settlementRef: string | null;
  status: Generated<PaymentAccountStatus>;
  tenantId: string | null;
}

export interface PersonalOffers {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  customerId: string;
  id: Generated<string>;
  intent: Generated<string>;
  locationId: string;
  normalPrice: number;
  serviceId: string;
  specialPrice: number;
  status: Generated<string>;
  tenantId: string;
  validUntil: Timestamp;
  variantId: string | null;
}

export interface PlatformNotices {
  audience: Generated<string>;
  body: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  refId: string | null;
  tenantId: string | null;
  title: string;
}

export interface PremiumOffers {
  candidates: Json;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  employeeId: string | null;
  endAt: string;
  id: Generated<string>;
  locationId: string;
  normalPrice: number;
  pct: number;
  price: number;
  recId: string | null;
  serviceId: string;
  stage: Generated<number>;
  startAt: string;
  status: Generated<string>;
  tenantId: string;
  variantId: string | null;
}

export interface ProductCategories {
  id: Generated<string>;
  name: string;
  parentId: string | null;
  sort: Generated<number>;
}

export interface Products {
  active: Generated<boolean>;
  categoryId: string | null;
  cost: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  img: string | null;
  name: string;
  own: Generated<boolean>;
  price: Generated<number>;
  sellerLegalEntityId: string | null;
  sizeAmount: number | null;
  sizeUnit: string | null;
  sku: string | null;
  supplierProductId: string | null;
  tenantId: string;
  use: string | null;
  vat: Generated<number>;
}

export interface PurchaseOrderLines {
  dmg: Generated<number>;
  free: Generated<number>;
  id: Generated<string>;
  orderId: string;
  price: number;
  qty: number;
  recv: Generated<number>;
  sort: Generated<number>;
  supplierProductId: string;
  tenantId: string;
}

export interface PurchaseOrders {
  byName: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  expected: Timestamp | null;
  id: Generated<string>;
  locationId: string;
  offerId: string | null;
  ref: string;
  status: Generated<PurchaseOrderStatus>;
  supplierId: string;
  supplierNote: Generated<string>;
  tenantId: string;
  track: Generated<string>;
}

export interface RefreshTokens {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  expiresAt: Timestamp;
  familyId: string;
  id: Generated<string>;
  revokedAt: Timestamp | null;
  rotatedAt: Timestamp | null;
  tenantId: string;
  tokenHash: string;
}

export interface Registrations {
  businessId: string | null;
  draft: Json;
  emailSentAt: Timestamp | null;
  emailToken: Generated<string>;
  emailVerifiedAt: Timestamp | null;
  hqReason: string | null;
  id: Generated<string>;
  log: Generated<Json>;
  resubmitToken: Generated<string>;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  status: Generated<RegistrationStatus>;
  ts: Generated<Timestamp>;
}

export interface Roles {
  baseRoleId: string | null;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  locked: Generated<boolean>;
  name: string;
  perms: Generated<Json>;
  std: Generated<boolean>;
  tenantId: string;
}

export interface ScheduleExceptions {
  createdAt: Generated<Timestamp>;
  endDate: Timestamp | null;
  holidayId: string | null;
  id: Generated<string>;
  locationId: string;
  periods: Json | null;
  reason: string | null;
  source: Generated<ScheduleExceptionSource>;
  startDate: Timestamp;
  tenantId: string;
  type: ScheduleExceptionType;
}

export interface SchemaMigrations {
  version: string;
}

export interface SearchConfig {
  activatedAt: Timestamp | null;
  activatedBy: string | null;
  activatedByName: Generated<string>;
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  createdByName: Generated<string>;
  id: Generated<string>;
  note: Generated<string>;
  payload: Json;
  version: number;
}

export interface SearchDocuments {
  categoryId: string | null;
  display: string;
  kind: string;
  norm: string;
  refId: string;
  salonName: string;
  salonSlug: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface SearchMisses {
  asked: Generated<number>;
  day: Generated<Timestamp>;
  firstAt: Generated<Timestamp>;
  how: string;
  lastAt: Generated<Timestamp>;
  norm: string;
  results: number;
}

export interface ServiceCategories {
  cardImage: string | null;
  icon: string | null;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  sort: Generated<number>;
}

export interface ServiceCategoryTerms {
  categoryId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  lang: string;
  norm: Generated<string>;
  term: string;
}

export interface ServiceModifierGroups {
  id: Generated<string>;
  name: string;
  required: Generated<boolean>;
  serviceId: string;
  sort: Generated<number>;
  tenantId: string;
  type: Generated<ModifierGroupType>;
}

export interface ServiceModifierOptions {
  durationMin: Generated<number>;
  groupId: string;
  id: Generated<string>;
  name: string;
  price: Generated<number>;
  sort: Generated<number>;
  tenantId: string;
}

export interface ServiceRecipes {
  productId: string;
  qtyAmount: Numeric;
  serviceId: string;
  tenantId: string;
}

export interface Services {
  categoryId: string | null;
  createdAt: Generated<Timestamp>;
  durationMin: number;
  id: Generated<string>;
  name: string;
  online: Generated<boolean>;
  pos: Generated<boolean>;
  prepMin: number | null;
  price: number;
  resetMin: number | null;
  sort: Generated<number>;
  status: Generated<ServiceStatus>;
  tenantId: string;
  vat: Generated<number>;
}

export interface ServiceVariants {
  durationMin: number;
  id: Generated<string>;
  label: string;
  price: number;
  serviceId: string;
  sort: Generated<number>;
  std: Generated<boolean>;
  tenantId: string;
}

export interface StockMovements {
  actorEmployeeId: string | null;
  at: Generated<Timestamp>;
  id: Generated<string>;
  kind: StockMovementKind;
  locationId: string;
  note: string | null;
  productId: string;
  qty: number;
  ref: string | null;
  tenantId: string;
}

export interface SupplierBrands {
  brandId: string;
  supplierId: string;
}

export interface SupplierConnections {
  connected: Timestamp | null;
  customerNo: Generated<string>;
  locationIds: Generated<string[]>;
  note: Generated<string>;
  share: Generated<Json>;
  status: Generated<string>;
  supplierId: string;
  tenantId: string;
}

export interface SupplierNotifications {
  body: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  refId: string | null;
  supplierId: string;
  title: string;
}

export interface SupplierProducts {
  active: Generated<boolean>;
  brand: Generated<string>;
  buy: Generated<number>;
  category: Generated<string>;
  descr: Generated<string>;
  ean: Generated<string>;
  id: Generated<string>;
  lead: Generated<string>;
  moq: Generated<number>;
  name: string;
  ownSize: number | null;
  ownUnit: string | null;
  pack: Generated<number>;
  rrp: Generated<number>;
  sample: Generated<boolean>;
  size: Generated<string>;
  sku: Generated<string>;
  stock: Generated<number>;
  supplierId: string;
  use: Generated<string>;
  vat: Generated<number>;
}

export interface SupplierPromotions {
  active: Generated<boolean>;
  audience: Generated<string>;
  brand: Generated<string>;
  ends: Timestamp;
  id: Generated<string>;
  kind: Generated<string>;
  minOrder: Generated<number>;
  per: Generated<number>;
  productIds: Generated<string[]>;
  starts: Timestamp;
  supplierId: string;
  terms: Generated<string>;
  title: string;
  usageLimit: Generated<number>;
  value: Generated<number>;
}

export interface SupplierRoles {
  id: string;
  locked: Generated<boolean>;
  name: string;
  perms: Generated<Json>;
  scope: Generated<string>;
  std: Generated<boolean>;
}

export interface Suppliers {
  avatar: string | null;
  contact: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lead: Generated<string>;
  manager: Generated<string>;
  minOrder: Generated<number>;
  name: string;
  rating: Numeric | null;
  terms: Generated<string>;
  territory: Generated<string>;
  type: Generated<string>;
  verified: Generated<boolean>;
}

export interface SupplierUsers {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  passwordHash: string;
  role: Generated<string>;
  status: Generated<string>;
  supplierId: string;
}

export interface SupportTickets {
  category: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<string>;
  lastActor: Generated<string>;
  messages: Generated<Json>;
  origin: string;
  originName: Generated<string>;
  replyTo: Generated<string>;
  status: Generated<SupportStatus>;
  subject: string;
  supplierId: string | null;
  tenantId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface TaxRules {
  id: Generated<string>;
  itemClass: string;
  legalEntityId: string | null;
  taxProfileId: string | null;
  tenantId: string | null;
}

export interface UserCredentials {
  employeeId: string;
  passwordHash: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Widgets {
  accent: Generated<string>;
  btnStyle: Generated<string>;
  cancelPolicy: Generated<string>;
  categories: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  deposit: Generated<string>;
  domains: Generated<string[]>;
  id: Generated<string>;
  lang: Generated<string>;
  locationIds: Generated<string[]>;
  name: string;
  publishableKey: string;
  radius: Generated<string>;
  startStep: Generated<string>;
  status: Generated<WidgetStatus>;
  tenantId: string;
  theme: Generated<string>;
}

export interface DB {
  appointmentHistory: AppointmentHistory;
  appointments: Appointments;
  assistantActions: AssistantActions;
  assistantDrafts: AssistantDrafts;
  auditLog: AuditLog;
  brands: Brands;
  businessCategories: BusinessCategories;
  businesses: Businesses;
  categoryRequests: CategoryRequests;
  checkoutItems: CheckoutItems;
  checkouts: Checkouts;
  clientCustomerLinks: ClientCustomerLinks;
  clientFavourites: ClientFavourites;
  clientNotifications: ClientNotifications;
  clientPaymentMethods: ClientPaymentMethods;
  clientUsers: ClientUsers;
  combos: Combos;
  customerActivity: CustomerActivity;
  customers: Customers;
  discountCodes: DiscountCodes;
  employeeLocations: EmployeeLocations;
  employees: Employees;
  employeeSignInLinks: EmployeeSignInLinks;
  employeeSkills: EmployeeSkills;
  empTimings: EmpTimings;
  giftCards: GiftCards;
  holds: Holds;
  holidayCalendarYears: HolidayCalendarYears;
  holidays: Holidays;
  hqRoles: HqRoles;
  hqUsers: HqUsers;
  integrationEvents: IntegrationEvents;
  invoiceCounters: InvoiceCounters;
  invoiceLines: InvoiceLines;
  invoices: Invoices;
  lastMinuteOffers: LastMinuteOffers;
  legalEntities: LegalEntities;
  legalEntityLocations: LegalEntityLocations;
  locationCatalogProducts: LocationCatalogProducts;
  locationCatalogServices: LocationCatalogServices;
  locationCatalogVariants: LocationCatalogVariants;
  locationLifecycleLog: LocationLifecycleLog;
  locations: Locations;
  loyaltyConfig: LoyaltyConfig;
  loyaltyLedger: LoyaltyLedger;
  mailOutbox: MailOutbox;
  memberRecs: MemberRecs;
  merchantTransactions: MerchantTransactions;
  paymentAccounts: PaymentAccounts;
  personalOffers: PersonalOffers;
  platformNotices: PlatformNotices;
  premiumOffers: PremiumOffers;
  productCategories: ProductCategories;
  products: Products;
  purchaseOrderLines: PurchaseOrderLines;
  purchaseOrders: PurchaseOrders;
  refreshTokens: RefreshTokens;
  registrations: Registrations;
  roles: Roles;
  scheduleExceptions: ScheduleExceptions;
  schemaMigrations: SchemaMigrations;
  searchConfig: SearchConfig;
  searchDocuments: SearchDocuments;
  searchMisses: SearchMisses;
  serviceCategories: ServiceCategories;
  serviceCategoryTerms: ServiceCategoryTerms;
  serviceModifierGroups: ServiceModifierGroups;
  serviceModifierOptions: ServiceModifierOptions;
  serviceRecipes: ServiceRecipes;
  services: Services;
  serviceVariants: ServiceVariants;
  stockMovements: StockMovements;
  supplierBrands: SupplierBrands;
  supplierConnections: SupplierConnections;
  supplierNotifications: SupplierNotifications;
  supplierProducts: SupplierProducts;
  supplierPromotions: SupplierPromotions;
  supplierRoles: SupplierRoles;
  suppliers: Suppliers;
  supplierUsers: SupplierUsers;
  supportTickets: SupportTickets;
  taxRules: TaxRules;
  userCredentials: UserCredentials;
  widgets: Widgets;
}
